### ISSUE TITLE
모임 상세 페이지 댓글 수정 API 확인 요청

### ISSUE THREAD

**Issue by WooDaeHyun** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#108]
### 버그설명

- 모임 상세 페이지 댓글 수정 API 호출시 요청과 응답이 200 OK로 받아지는데 댓글 내용 수정은 되지 않고 있어 확인 부탁립니다!🥹

### 스크린샷

- 통신은 정상적으로 이뤄지는 것 같습니다.
<img width="753" alt="스크린샷 2023-03-11 오전 4 14 33" src="https://user-images.githubusercontent.com/113018070/224405770-0803cb45-2e40-48a8-8c6a-fbad49659b32.png">

- commentId와 comment(수정된 댓글)도 정상적으로 담겨서 보내지는 것 같습니다.
<img width="753" alt="스크린샷 2023-03-11 오전 4 15 51" src="https://user-images.githubusercontent.com/113018070/224405985-fc645d7c-5e8a-4468-a07a-c6f800dabd1a.png">

-응답을 보면 contents에 수정된 내용이 반영되지 못한 것 같아서 확인 부탁드리겠습니다. 저도 제가 잘못 작성한게 있는지 다시 확인해보겠습니다~
<img width="974" alt="스크린샷 2023-03-11 오전 4 16 57" src="https://user-images.githubusercontent.com/113018070/224406197-ddfe8fa9-3ea7-4e4f-8482-d16758ac3384.png">

감사합니다~☺️

**Comment by devYSK** [comment]
@WooDaeHyun 
해당 버그 찾아 수정하였습니다.
다음과 같은 변경사항이 있습니다. 
api path : patch - /api/book-groups/{groupId}/comments/{commentId}
body : 바뀔 내용

* 바뀐내용 
  *  /api/book-groups/{groupId}/ comment -> comments 복수형으로 수정하였습니다
  * path에 commentId를 추가하였습니다 
  * body에서 commentId를 제거하였습니다.
  * 요청자가 댓글의 주인이 아니라면, 403 응답를 반환합니다. 에러코드는 BGC9입니다.


@tinajeong @youngjijang

**Comment by devYSK** [comment]
해당 이슈 close 합니다.
