### ISSUE TITLE
모임 상세 페이지 비밀번호 입력하여 모임 가입시 이슈 발생

### ISSUE THREAD

**Issue by WooDaeHyun** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#110]
### 버그설명

- 모임 생성시에 입력한 비밀번호가 잘 전달되는 것을 확인했고,
- 그 후 모임에 참여하기 위해 비밀번호를 입력하여 모임 참여 API를 호출할 때 '옳바른 정답'이 잘 전달되는것 까지 확인했으나
- reponse message에 정답이 틀리다는 응답이 내려오고 있습니다. 확인 부탁드려요~

### 스크린샷

- 혹시 필드 key 값이 모임 생성시에는 joinPasswd로 들어가고 모임 가입시에는 joinPassword이던데 이 부분 때문일까요?!~

- 모임 생성시 입력한 비밀번호가 정상적으로 잘 전달됩니다.
<img width="394" alt="모임 생성 API 호출" src="https://user-images.githubusercontent.com/113018070/224473279-6feefcb6-cc5d-49a6-846d-b07ddb0dffd8.png">

- 정답을 입력 후 모임 참여하기 API를 호출하면 옳바른 정답이 잘 전달됩니다.
<img width="974" alt="스크린샷 2023-03-11 오후 5 16 02" src="https://user-images.githubusercontent.com/113018070/224473344-23d6da23-233f-4333-a99b-ce19a90c5c59.png">

- 응답 메세지에 비밀 번호가 옳바르지 않다는 내용이 내려오면서 에러가 발생합니다.
<img width="974" alt="스크린샷 2023-03-11 오후 5 17 16" src="https://user-images.githubusercontent.com/113018070/224473399-a5505776-6272-47ef-968a-581052d7e9d7.png">

확인 부탁드립니다~

**Comment by youngjijang** [comment]
수정했습니다~! 머지 완료되면 다시 확인 부탁드려요!
이름 때문은 아니지만 이름도 통일했습니다ㅎㅎ
