### ISSUE TITLE
로그인 사용자 책장 추천, 책 추천 api에서 받는 jobGroup 파라미터 형식에 대한 이슈

### ISSUE THREAD

**Issue by harryk-im** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#111]
### 기능명
직군별 책장 요약 리스트(로그인 사용자 추천)
책 추천(직군별 많이 꽂혀있는 순)

### 세부사항
두 api에서 파라미터로 받는 로그인한 유저의 직군(jobGroup)이
하나는 한글, 다른 하나는 영어로만 받게 되어있는것같아요.

둘 다 jobGroup을 한글 또는 영어로 받을 수 있게 통일 시켜주실수 있는지 궁금합니다...!

### 기한
빠르면 좋아요~

**Comment by youngjijang** [comment]
영어로 통일하도록 수정하겠습니다!
