### ISSUE TITLE
로그인하지 않은 사용자도 책 코멘트 목록을 볼 수 있어야 해요

### ISSUE THREAD

**Issue by gxxrxn** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#117]
### 버그설명
[책 리뷰 목록 조회 api 명세](http://13.125.121.172/docs/index.html#_%EC%B1%85_%EB%A6%AC%EB%B7%B0_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C)

로그인하지 않은 사용자도 책 코멘트들을 볼 수 있게 하자고 논의했었는데, 현재는 요청 헤더에 accessToken이 꼭 담겨있어야해요.
헤더에 토큰이 없어도 에러가 발생하지 않고, writtenByCurrentUser 필드가 모두 false인 코멘트들이 응답으로 오도록 수정되면 좋을 것 같아요!

**Comment by devYSK** [comment]
해당이슈 확인하였습니다.

**Comment by devYSK** [comment]
해당 이슈 담당자 변경합니당 @youngjijang

**Comment by WooDaeHyun** [comment]
모임 상세 조회, 모임 댓글 리스트 조회도 로그인 하지 않은 사용자도 볼 수 있어야 할 것 같아요 ☺️ 감사합니다~
