### ISSUE TITLE
dev.api.dadok.site 로 oauth 요청을 보내면 에러가 발생해요.

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#122]
### 버그설명

dev.api.dadok.site 로 oauth 요청을 보내면 에러가 발생해요.

### 원하는 결과

dev.api.dadok.site 로 oauth 요청을 보내면 로그인에 성공합니다.

### 스크린샷

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/48359052/224561827-342f2733-1660-4b19-8b78-e4809e1cf807.png">

**Comment by minjongbaek** [comment]
카카오 API에 도메인이 등록되어야 하는건 아닐까요?

**Comment by devYSK** [comment]
@minjongbaek 등록 하였습니다 확인 부탁드립니다~!

**Comment by minjongbaek** [comment]
엇..! 동일한 에러가 발생하는데 다시 한 번 확인 부탁드려요

**Comment by devYSK** [comment]
에러 해결하였습니다.

**Comment by minjongbaek** [comment]
확인했습니다. 감사합니다.
