### ISSUE TITLE
모임 가입시 "책장 책 조회" api에 자동으로 업데이트가 안됩니다.

### ISSUE THREAD

**Issue by harryk-im** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#125]
### 목적
모입 가입시 "책장 책 조회" api에 책이 꽂아지지 않습니다.

### 작업
"자기 자신 책장 조회(프로필)" api에는 업데이트 되는것으로 확인됩니다.
다만 "책장 책 조회" api에는 꽂아진 책이 업데이트 되지 않는것으로 확인되었습니다.

### 완료조건
책 꽂기 및 모임 가입시에 api들에 정상적으로 업데이트가 되면 완료!

**Comment by devYSK** [comment]
@hanyugeon 
해당 이슈 확인하여 데이터베이스 조회 및 서버 쿼리 로그 확인 결과 기능에는 문제가 없음으로 보입니다.
api 요청시 cursorId가 10으로 고정이 되어 있는데, null로 한번 보내봐주시길 부탁 드리겠습니다. 

커서 기반 페이지네이션에서는 cursorId = null, DESC -> 최신순, cursorId=null, ASC - > 가장 오래된 순 입니다.

**Comment by harryk-im** [comment]
@devYSK 
null인경우에는 파라미터가 잘못되었다고 응답이 오네요..!
근데 cursorId를 999로 해보니 모든 책이 잘 나오는걸로 확인되었네요...!
늦은시간까지 진짜 고생많으십니다, 빠르게 대응 해주셔서 정말 감사합니다!

**Comment by tinajeong** [comment]
@hanyugeon 확인결과 조회로직에는 문제가 없습니다! 파라미터를 `null`로 명시하지 않고 빈칸으로 두면 정상 조회되는 것 확인하였습니다.
`bookshelves/24/books?pageSize=10&bookCursorId=&sortDirection=DESC`의 형태로 전송바랍니다.

**Comment by tinajeong** [comment]
프론트 쪽 확인 완료되어 close 하겠습니다.
