### ISSUE TITLE
책 생성 API의 요청 권한을 anonymous로 변경 가능할까요?

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#126]
### 기능명

책 생성 API의 요청 권한을 anonymous로 변경 가능할까요?

### 세부사항

비회원도 책을 검색해서 클릭하면 상세페이지로 접근할 수 있습니다.
책을 클릭했을 때 책 생성 API를 호출하는데 API의 권한을 anonymous로 변경 가능할까요?
http://dev.api.dadok.site/docs/index.html#_%EC%B1%85_%EC%83%9D%EC%84%B1

**Comment by youngjijang** [comment]
넵~ 추가했습니다!

**Comment by minjongbaek** [comment]
확인했습니다. 감사합니다~
