### ISSUE TITLE
refresh token 쿠키 도메인 수정 요청

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#128]
### 기능명

서버에 HTTPS 적용을 해주실 수 있을까요?

### 세부사항

서버에서 보내는 쿠키를 https://dev.dadok.site 에서 읽지 못하는 것 같습니다.

http://dev.api.dadok.site 으로 로그인 요청을 보냈을 때 http://dev.api.dadok.site 의 cookie에 aceessToken이 담기는 것을 보니 로직에는 문제가 없을 것 같아요.

의심이 되는 부분은 https <-> http 프로토콜이 달라서 그런 것은 아닐까 싶어서 요청 드립니다.

---

만약 인증서를 적용하는 일에 공수가 많이 든다면, cookie domain을 우선 dadok.site로 바꿔봐도 좋을 것 같아요!

### 기한

빠를 수록 좋아요.

**Comment by devYSK** [comment]
@minjongbaek 해당 이슈 확인하였습니다 처리 후 말씀 드릴게요

**Comment by devYSK** [comment]
@minjongbaek 서버 https 적용 시켜 놓았습니다. http로 요청해도 https로 변경되어 요청 전달됩니다.

**Comment by minjongbaek** [comment]
@devYSK 확인이 늦었습니다. refresh_token 만 확인이 안되는데 domain도 수정이 되었을까요? 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/48359052/224709191-539ea7ce-0934-4976-97c3-d46279712847.png">

**Comment by minjongbaek** [comment]
확인되었습니다. 감사합니다~
