### ISSUE TITLE
리드미 작성

### ISSUE THREAD

**Issue by tinajeong** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#129]
### 목적
- 프로젝트 제출 전 리드미 작성

### 작업
- 리드미 작성

### 완료조건
- 필요한 항목 작성 완료 시

### 리드미 참고

네이버의 차트 라이브러리
- 데모이미지가 있어 어떤 기능이 있는지 파악하기 좋음 : https://github.com/naver/billboard.js

뉴스레터
- 기록을 날짜 별로 보여주는 토글 : https://github.com/naver/fe-news

우테코 팀프로젝트

- 팀문화를 적은게 인상적 : https://github.com/woowacourse-teams/2022-smody
- gif 데모가 있듬 : https://github.com/woowacourse-teams/2021-pick-git

**Comment by youngjijang** [comment]
<img width="960" alt="KakaoTalk_Photo_2023-03-15-13-20-03-1" src="https://user-images.githubusercontent.com/100327413/225206668-df7c5b38-5c40-4fdc-b8bf-14101966cf1b.png">
