### ISSUE TITLE
권한이 필요한 API 조회시 에러코드 추가 요청

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#134]
### 기능명

인증 처리 없이 인증이 필요한 API를 조회하면 아래 사진 처럼 403 status 와 error code null이 반환됩니다.

테스트는 내 프로필 조회 API를 요청했습니다.

혹시 권한이 필요한 API 조회시에 에러코드를 추가해주실 수 있을까요~?

![image](https://user-images.githubusercontent.com/48359052/224776400-ecce1a95-c577-4b1e-a189-1174b8de826d.png)

**Comment by devYSK** [comment]
![image](https://user-images.githubusercontent.com/41531594/224782726-f30170be-8e8c-47aa-90d9-59ed5ac4ec77.png)

해당 예외는 AccessDenied로 'A7' 이라는 에러 코드로 정의하여 추가하였습니다.
