### ISSUE TITLE
비회원이 사용자의 프로필을 조회할 수 없어요.

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#136]
### 버그설명

비회원이 사용자의 프로필을 조회할 수 없어요.

### 원하는 결과

비회원도 사용자의 프로필을 조회할 수 있어야 해요.

### 스크린샷

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/48359052/224831782-9407b55e-b489-433a-9065-ec05e7e63af6.png">

**Comment by devYSK** [comment]
@minjongbaek 해당 이슈 수정하였습니다

**Comment by minjongbaek** [comment]
확인했습니다. 감사합니다.
