### ISSUE TITLE
도서 검색 API의 결과에 문제가 있어요

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#146]
### 버그설명

[API 문서](https://api.dev.dadok.site/docs/index.html#_%EC%B1%85_%EA%B2%80%EC%83%89)를 보고 **page는 offset과 같고 pageSize**는 **offset 지점으로부터 가져올 아이템의 수**라고 생각했어요.

그런데 page가 pageSize 처럼 동작을 하는 것으로 보여요.

증상을 보고 의심되는 원인은, 카카오 API 서버로 요청을 보낼때 page, size 파라미터를 클라이언트에서 전달하는 page로 보내고 있는 것 같아요.

### 원하는 결과

page = 2, pageSize = 10 을 보내면, 10개씩 페이징된 페이지 중 2페이지를 가져와야 해요.

### 실제 결과

page = 2, pageSize = 10을 보내면, 2개씩 페이징된 페이지 중 2페이지를 가져와요.

### 스크린샷

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/48359052/230542939-ebd87577-4ed1-4106-8e1d-5430dbcabc03.png">

**Comment by minjongbaek** [comment]
아! 그리고 response fileds에 request params에 있던 page 값을 그대로 받을 수 있을까요?

**Comment by tinajeong** [comment]
@minjongbaek 확인해보겠습니다~ response field에 page 데이터는 함께 보내는 것 가능합니다!
