### ISSUE TITLE
내 책장에 책을 꽂지 않고 코멘트를 남기려고 하면 500에러가 와요.

### ISSUE THREAD

**Issue by gxxrxn** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#151]
### 버그설명
내 책장에 책을 꽂지 않았는데 코멘트를 남기려고 하면 핸들링되지 않은 500에러가 오는 것 같아요!

### 원하는 결과
적절한 커스텀 에러 코드를 응답으로 보내주시면 감사하겠습니다!
프론트 측에서도 코드에 반영을 해야해서 어떤 에러 코드가 전달되는지 살짝 언급해주시면 감사하겠습니다..ㅎㅎ 🙇🏻‍♀️

### 실제 결과
<img width="762" alt="스크린샷 2023-04-11 오전 1 30 28" src="https://user-images.githubusercontent.com/57716832/230946574-f9174090-c322-4784-94a3-485ccd19f986.png">

**Comment by youngjijang** [comment]
@tinajeong 확인부탁해용

**Comment by tinajeong** [comment]
이미 핸들링 처리는 되어 있는데, 제대로 동작하지 않는것 같아요. 확인해볼게요

**Comment by tinajeong** [comment]
```
{"status":400,"message":"이미 남긴 도서 코멘트에 있습니다.","code":"BC1","timestamp":"2023-04-12 00:08:27","errors":null,"path":"/api/books/421/comments"}
```
위 내용 참고 부탁드립니다~
