### ISSUE TITLE
도서 검색 기능 및 최근 검색어 기능 관련 이슈

### ISSUE THREAD

**Issue by WooDaeHyun** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#161]
### 목적

- 비로그인 유저의 경우에도 도서 검색이 가능하게 동작 했었는데, 현재 비로그인 유저의 경우 도서 검색 API 호출시 Error가 발생합니다. 아마 최근 검색어 관련 API 수정하는 과정에서 이런 이슈가 발생한 것 같은데 확인 부탁드려용~☺️

- 최근 검색어 API를 호출하여 받아온 데이터에 단어들이 중복되어 들어가 있습니다. 검색을 했을 때 해당 검색어와 관련된 도서가 하나 이상 검색 된 경우에는 최근 검색어로 받아오는 데이터에 똑같은 단어가 두 번 들어가고, 만약 검색어를 입력했을때 검색 된 도서가 하나도 없는 경우에는 단어가 한 번만 들어가네요! 중복부분 처리와 관련해서 프론트에서 처리를 해야할까요?? 

@tinajeong

**Comment by tinajeong** [comment]
확인해보겠습니다~

**Comment by tinajeong** [comment]
익명 유저와 중복이슈 해결 완료 되었습니다!
