### ISSUE TITLE
최근 검색어 관련 이슈

### ISSUE THREAD

**Issue by WooDaeHyun** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#162]
### 버그설명

- 현재 로그인 상태에서 최근 검색어 데이터를 받아온 후 로그아웃을 하고 다시 검색 페이지로 들어가면 똑같은 로그아웃을 한 상태에서도 최근 검색어 키워드들을 받아오고 있습니다. 
- 로그인 한 유저의 경우 토큰을 헤더에 담아 보내고 비로그인 유저의 경우 빈 값을 받아 오는 것으로 알고 있는데 비로그인 유저의 경우 헤더에 토큰이 담기지 않았음에도 최근 검색어 데이터를 빈값이 아닌 로그인한 상태에서 받아온 데이터와 동일한 데이터를 받아 오고 있습니다. 

- 확인 부탁드려용~😁

@tinajeong

**Comment by tinajeong** [comment]
말씀하신 이슈 해결되었습니다!
