### ISSUE TITLE
책 검색 API를 두 개로 나눌 수 있을까요?

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-web-devcourse/Team-Gaerval-Dadok-BE#169]
### 기능명

책 검색 API를 미리보기, 결과 두 개로 나눌 수 있을까요?

### 세부사항

[책 검색 플로우 수정](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/issues/331)을 작업 중에 요청 사항이 있어 이슈 남겨요!

현재는 키 입력이 발생할 때 마다 API를 호출하고 있는데, 의도하지 않은 키워드가 최근 검색어에 등록되는 문제가 있어요.

예를들면 '자바의 정석'을 검색하려고 하는데 '자바ㅇ' 까지 검색하다가 사용자가 입력을 멈추면 '자바ㅇ'가 최근 검색어에 추가되고 있어요.

밀리의 서재를 참고해서 키 입력에 따른 검색 결과 미리보기는 책 제목을 텍스트로만 보여주고 결과는 기존과 같은 화면을 보여주면 어떨까 하는데 어떻게 생각하시나요?

<div style="display:flex">
<img src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-BE/assets/48359052/f32c082e-c5b2-4b45-9e9f-fbcc0a347f7c" width=200 />
<img src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-BE/assets/48359052/06a95803-c26a-44d3-8f14-6b14fd1c33d7" width=200 />
<img src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-BE/assets/48359052/c1535e0d-a7f9-4d4b-af10-753bb443ab7e" width=200 />
<img src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-BE/assets/48359052/875749b8-8e23-4f0e-af68-54f2f575a494" width=200 />
</div>

**Comment by minjongbaek** [comment]
@devYSK @youngjijang @tinajeong 혹시 내용이 이해가 안되거나 회의가 필요하다면 말씀해주세요~

**Comment by tinajeong** [comment]
@minjongbaek 어려운 작업은 아니지만, 미리보기 api 결과에는 어떤값들이 필요한지 알 수 있을까요?

**Comment by minjongbaek** [comment]
@tinajeong 책 제목 정도만 생각하고 있습니다.

그런데, 검색된 책을 클릭하면 책 생성 api를 호출하고 있습니다. 미리보기 요소 중 하나를 클릭해서 상세페이지로 넘어가는 걸 생각하면 책 생성 api에 포함해야할 정보도 있어야 할 것 같아요..!

**Comment by tinajeong** [comment]
@minjongbaek `미리보기`도 `책 상세페이지`로 이동하는 시나리오가 있다는 말씀이신거죠!
아래 두가지 제안을 추가로 드리니 지금 요청주신 엔드포인트 분리 방안과 함께 검토후 말씀해주세요!

- 엔드포인트를 두개로 나누지 않고, 최근검색어를 저장하겠다는 request parameter 를 현재 end point에 추가하기
- 디바운싱 타임을 없애고, 명시적인 검색 액션을 통한 처리

**Comment by minjongbaek** [comment]
@tinajeong 네 맞아요! 미리보기를 보여주려면 명시적인 액션으로 처리하는 것 보다 request parameter를 활용하는게 좋을 것 같아요!
